export const mockAnimals = [
  {
    id: "1",
    name: "Bella",
    species: "dog",
    breed: "Labrador",
    age_years: 4,
    age_category: "adult",
    size: "med",
    special_needs: false,
    photo_url: "https://placedog.net/600/400?id=1",
    status: "available",
  },
  {
    id: "2",
    name: "Max",
    species: "cat",
    breed: "Siamese",
    age_years: 10,
    age_category: "senior",
    size: "small",
    special_needs: true,
    photo_url:
      "https://images.pexels.com/photos/45201/kitty-cat-kitten-pet-45201.jpeg",
    status: "available",
  },
  {
    id: "3",
    name: "Charlie",
    species: "dog",
    breed: "Beagle",
    age_years: 1,
    age_category: "young",
    size: "large",
    special_needs: false,
    photo_url: "https://placedog.net/600/400?id=2",
    status: "available",
  },
  {
    id: "4",
    name: "Luna",
    species: "rabbit",
    breed: "Holland Lop",
    age_years: 2,
    age_category: "adult",
    size: "small",
    special_needs: false,
    photo_url:
      "https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg",
    status: "available",
  },
];
